### ISSUE TITLE
Internal User Database + LDAP: ElasticsearchSecurityException[No user kibanaserver found] 

### ISSUE THREAD

**Issue by weand** [opendistro-for-elasticsearch/security-advanced-modules#59]
We have LDAP and Internal User Storage configured in parallel for http authentication. Use Case is,  that users accessing Kibana can use their LDAP Credentials and the communication between Kibana Server and Elasticsearch is secured with internal user (and also other Services accessing the Elasticsearch REST API use service users maintained in internal user database).

The authentication works successfully, but each time the Kibana Server tries to authenticate for accessing Elasticsearch this *ERROR* log line pops up in log: `org.elasticsearch.ElasticsearchSecurityException: ElasticsearchSecurityException[No user kibanaserver found]` with `com.amazon.dlic.auth.ldap.backend.LDAPAuthorizationBackend` in stacktrace. 

We already use Internal Auth Backend with `order: 1` and LDAP Auth Backenb with `order: 2`:
```
    authc:
      basic_internal_auth_domain:
        http_enabled: true
        transport_enabled: false
        order: 1
        http_authenticator:
          type: basic
          challenge: true
        authentication_backend:
          type: intern
      ldap:
        http_enabled: true
        transport_enabled: false
        order: 2
        http_authenticator:
          type: basic
          challenge: true
        authentication_backend:
          # LDAP authentication backend (authenticate users against a LDAP or Active Directory)
          type: ldap
          ...
```

Expected behavior: LDAP ist not queried at all when authentication against Internal User Storage already succeeded. Or that the message is suppressed. Or that the message is DEBUG level.

Full Stacktrace:

```node1     | [2019-11-25T15:15:04,511][ERROR][c.a.o.s.a.BackendRegistry] [node1] Cannot retrieve roles for User [name=kibanaserver, roles=[admin], requestedTenant=null] from ldap due to ElasticsearchSecurityException[ElasticsearchSecurityException[No user kibanaserver found]]; nested: ElasticsearchSecurityException[No user kibanaserver found];
node1     | org.elasticsearch.ElasticsearchSecurityException: ElasticsearchSecurityException[No user kibanaserver found]
node1     |     at com.amazon.dlic.auth.ldap.backend.LDAPAuthorizationBackend.fillRoles(LDAPAuthorizationBackend.java:854) ~[opendistro_security_advanced_modules-1.2.1.0.jar:1.2.1.0]
node1     |     at com.amazon.opendistroforelasticsearch.security.auth.BackendRegistry.authz(BackendRegistry.java:622) [opendistro_security-1.2.1.0.jar:1.2.1.0]
node1     |     at com.amazon.opendistroforelasticsearch.security.auth.BackendRegistry.access$000(BackendRegistry.java:84) [opendistro_security-1.2.1.0.jar:1.2.1.0]
node1     |     at com.amazon.opendistroforelasticsearch.security.auth.BackendRegistry$9.call(BackendRegistry.java:663) [opendistro_security-1.2.1.0.jar:1.2.1.0]
node1     |     at com.amazon.opendistroforelasticsearch.security.auth.BackendRegistry$9.call(BackendRegistry.java:655) [opendistro_security-1.2.1.0.jar:1.2.1.0]
node1     |     at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4875) [guava-25.1-jre.jar:?]
node1     |     at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527) [guava-25.1-jre.jar:?]
node1     |     at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2276) [guava-25.1-jre.jar:?]
node1     |     at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154) [guava-25.1-jre.jar:?]
node1     |     at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044) [guava-25.1-jre.jar:?]
node1     |     at com.google.common.cache.LocalCache.get(LocalCache.java:3951) [guava-25.1-jre.jar:?]
node1     |     at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4870) [guava-25.1-jre.jar:?]
node1     |     at com.amazon.opendistroforelasticsearch.security.auth.BackendRegistry.authcz(BackendRegistry.java:655) [opendistro_security-1.2.1.0.jar:1.2.1.0]
node1     |     at com.amazon.opendistroforelasticsearch.security.auth.BackendRegistry.authenticate(BackendRegistry.java:461) [opendistro_security-1.2.1.0.jar:1.2.1.0]
node1     |     at com.amazon.opendistroforelasticsearch.security.filter.OpenDistroSecurityRestFilter.checkAndAuthenticateRequest(OpenDistroSecurityRestFilter.java:146) [opendistro_security-1.2.1.0.jar:1.2.1.0]
...
```
