### ISSUE TITLE
Missing important parameter in OpenID configuration

### ISSUE THREAD

**Issue by miro-grapeup** [opendistro-for-elasticsearch/security-advanced-modules#63]
There is a quite well documented configuration settings for OpenID: https://opendistro.github.io/for-elasticsearch-docs/docs/security-configuration/openid-connect/ but it clearly misses the information that for openid the `openid_connect_idp` prefix is required:
https://github.com/opendistro-for-elasticsearch/security-advanced-modules/blob/e5d91955087c7365ac9a9ff33368521761976ee6/src/main/java/com/amazon/dlic/auth/http/jwt/keybyoidc/HTTPJwtKeyByOpenIdConnectAuthenticator.java#L57

**Comment by CodeGlitcher** [comment]
The openid_connect_ipd did not work for me.
I configured oidc as follows
```
         config:
            subject_key: unique_name
            roles_key: group
            openid_connect_url: "https://url to adfs/.well-known/openid-configuration"
            openid_connect_idp.enable_ssl: true
            openid_connect_idp.verify_hostnames: true
            openid_connect_idp.pemtrustedcas_filepath: "/usr/share/elasticsearch/config/ca.crt"
```
